pipeline {
    agent any
    tools {
        nodejs 'NodeJS 20.13.1'
    }
    environment {
        ANDROID_HOME = "C:\\Users\\hp\\AppData\\Local\\Android\\Sdk"
        GRADLE_HOME = "C:\\Users\\hp\\.gradle"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: 'bb0db85a-5202-4b1d-9e4c-19c10138d5ef', url: 'https://github.com/kelvin-manyengo-magwe/wakala.git'
            }
        }

        stage('Verify Node.js') {
            steps {
                sh 'node -v'  //verifying Node.js installation
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
                if (returnStatus != 0) {
                        error 'Failed to install dependencies!'
                    }
            }
        }

        stage('Build Android APK') {
            steps {
                    sh 'cd android && ./gradlew assembleDebug' //for development and debug version of the application
            }
        }

        stage('Archive APK') {
            steps {
                archiveArtifacts artifacts: 'android/app/build/outputs/apk/debug/app-debug.apk', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "APK Build Successful!"
        }
        failure {
            echo "APK Build Failed!"
        }
    }
}