pipeline {
    agent any

    environment {
        ANDROID_HOME = "C:/Users/hp/AppData/Local/Android/Sdk"
        GRADLE_HOME = "${env.WORKSPACE}/android/gradle"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: 'bb0db85a-5202-4b1d-9e4c-19c10138d5ef', url: 'https://github.com/kelvin-manyengo-magwe/wakala.git'
            }
        }

        stage('Set Up Node.js') {
            steps {
                script {
                    def nodejs = tool name: 'NodeJS 20.13.1', type: 'NodeJSInstallation' //Defining NodeJS version
                    env.PATH = "${nodejs}/bin:${env.PATH}"
                }
                sh 'node -v'  //verifying Node.js installation
            }
        }

        stage('Install Dependancies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Android APK') {
            steps {
                dir('android') {
                    sh './gradlew assembleDebug' //for development and debug version of the application
                }
            }
        }

        stage('Archive APK') {
            steps {
                archivArtifacts artifacts: 'android/app/build/outputs/apk/debug/app-debug.apk', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "APK Build Successful!"
        }
        failure {
            echo "APK Build Failed!"
        }
    }
}